### ISSUE TITLE
Action Not Working

### ISSUE THREAD

**Issue by yurijserrano** [umutphp/github-action-dynamic-profile-page#2]
Good Afternoon

I've followed all the procedures but I am receiving the following **error**:

![actionerror](https://user-images.githubusercontent.com/14169134/93520887-94833180-f905-11ea-99f2-87b9139eed59.png)

It's saying that the **password** was **not found** but on the main page just says that needs **repo** to work properly.

Below my **gadpp.yml** config can be seen:

```
on: [push]


jobs:
  gadpp_job:
    runs-on: ubuntu-latest
    name: Update GitHub Profile Page
    steps:
      - name: Push updates to my Github Profile Page
        uses: umutphp/github-action-dynamic-profile-page@v2
      - name: GADPP
        uses: ./
        id: gadpp
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          github-username: 'yurijserrano'
          user-email: 'yurijserrano@gmail.com'
```

Have a nice day

**Comment by yurijserrano** [comment]
I've found the problem, I didn't add the checkout so this way the pipeline was failing.

If someone goes through the same problem, below you can see the configuration that works correctly:

```
on: [push]


jobs:
  gadpp_job:
    runs-on: ubuntu-latest
    name: Update GitHub Profile Page
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: GADPP
        uses: umutphp/github-action-dynamic-profile-page@v2
        id: gadpp
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          github-username: 'yurijserrano'
          user-email: 'yurijserrano@gmail.com'
```

Have a nice week
