### ISSUE TITLE
Action executing uninterrupted

### ISSUE THREAD

**Issue by yurijserrano** [umutphp/github-action-dynamic-profile-page#3]
The action had to be executed only when there was a push, but it is being executed uninterruptedly (without any push being made), as can be seen below:

![action02](https://user-images.githubusercontent.com/14169134/93541152-fd7da000-f92b-11ea-9876-947c15dfd6c4.png)

I checked the documentation but there is nothing about it.

Have a nice day.

**Comment by umutphp** [comment]
Hi @yurijserrano ,

I am sorry for late response :(. Can you please also share the YML file of the action in your repository which causes the uninterrupted actions?

**Comment by yurijserrano** [comment]
No problem @umutphp 

I've used the **YML** below:

```
on: [push]


jobs:
  gadpp_job:
    runs-on: ubuntu-latest
    name: Update GitHub Profile Page
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: GADPP
        uses: umutphp/github-action-dynamic-profile-page@v2
        id: gadpp
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          github-username: 'yurijserrano'
          user-email: 'yurijserrano@gmail.com'
```

What I felt strange was that in the repository itself regarding your Github README profile you did not include this setting as you can see right below:

![case01](https://user-images.githubusercontent.com/14169134/94368671-d0fc1d80-00bb-11eb-9694-d7257222bc8e.png)

I am waiting to hear from you.

Have a nice day.
